{{- if .Values.profiles.additionalProfiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kbounce.fullname" . }}-profiles
  labels:
    {{- include "kbounce.labels" . | nindent 4 }}
data:
  profiles.yaml: |
    profiles:
{{ toYaml .Values.profiles.additionalProfiles | indent 6 }}
{{- end }}
