apiVersion: v1
kind: Service
metadata:
  name: {{ include "kbounce.fullname" . }}
  labels:
    {{- include "kbounce.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.proxy.port }}
      targetPort: wire
      protocol: TCP
      name: wire
    - port: {{ .Values.mgmt.port }}
      targetPort: mgmt
      protocol: TCP
      name: mgmt
  selector:
    {{- include "kbounce.selectorLabels" . | nindent 4 }}
